### ISSUE TITLE
Additional documentation useful for set up

### ISSUE THREAD

**Issue by zmek** [nhsengland/privfp-experiments#13]
Noting here additional items that would be useful to document / add. (I will create a PR when I've documented a few of these)

- [ ] In the generation notebook: the fact that the code is making API calls to the Ollama server. On a Mac M1, I had to download ollama as an application. This has to be running in order for the langchain commands to work
- [ ] Save output from generation notebook for use in extraction model
- [ ] Provide link to guidance on how to quantise a model (recognising this will be specific to user's environment)

**Comment by xiyaozhuang** [comment]
Currently working on documentation for the website to provide better setup instructions! In addition to your suggestions above, this will include:

- Synthea International with OpenJDK for generation of structured synthetic data
- CorrectMatch with Julia for risk scoring
